social_network/about/urls.py
from django.urls import path

from . import views
app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

social_network/posts/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('new', views.new_post, name='new_post'),

    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>', views.post_view, name='post'),
    path('<str:username>/<int:post_id>/edit',
         views.post_edit, name='post_edit'),
]

social_network/social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),

    path('about/', include('about.urls', namespace='about')),

]

social_network/users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),

]

social_network/about/models.py
from django.db import models

# Create your models here.

social_network/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=15, help_text='Введите Название', verbose_name='Название')
    slug = models.SlugField(unique=True)
    description = models.TextField(help_text='Введите Описание', verbose_name='Описание')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(help_text='Введите текст', verbose_name='Текст')
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        null=True,
        blank=True
        )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)

social_network/posts/forms.py
from django.forms import ModelForm
from .models import Post


class CreationForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {'text': 'Текст',
                  'group': 'Группа'
                  }

social_network/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

social_network/about/views.py
from django.views.generic import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

social_network/posts/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from .forms import CreationForm
from .models import Post, Group, User


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request,
                  'index.html',
                  {'page': page})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'group.html', {'group': group, 'page': page})


@login_required
def new_post(request):
    form = CreationForm(request.POST or None)

    if form.is_valid():
        form.instance.author = request.user
        form.save()
        return redirect('index')
    return render(request, 'new.html', {'form': form, 'edit': False})


def profile(request, username):
    profile = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=profile)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'profile.html', {'profile': profile, 'page': page})


@login_required
def post_view(request, username, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'post.html', {'post': post})


def post_edit(request, username, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user.username == username:
        form = CreationForm(request.POST or None, instance=post)
        if form.is_valid():

            form.save()
            return redirect('index')
        return render(request, 'new.html', {'form': form, 'edit': True, 'post': post})
    return redirect('index')

social_network/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from users.forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('signup')
    template_name = 'signup.html'

social_network/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Об авторе
                </div>
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Полезный короткий текст
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">
          <div class="card-text">
            <p>Текст страницы "Об авторе"</p>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

social_network/templates/about/tech.html
{%  extends "base.html" %}
{% block title %}О технологиях{% endblock %}
{% block content %}
{% load user_filters %}
{% if page.has_other_pages %}
    <nav>
        <ul class="pagination">
            {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo; Предыдущая</span>
                </li>
            {% endif %}
            {% for i in page.paginator.page_range %}
                {% if page.number == i %}
                    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Следующая &raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
{% endblock %}

social_network/templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The social network{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
{%include 'nav.html' %}
<main>
    <div class="container">
        <h1>{% block header %}The social network{% endblock %}</h1>
        {% block content %}
        {% endblock %}
    </div>
</main>
{%include 'footer.html' %}
</body>

</html>

social_network/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center">
        <a href="/about/author">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:darkviolet">Social</span> Network </p>
</footer>

social_network/templates/group.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}


{% for post in page %}
<h3>

    Автор: <a href="/{{ post.author.username }}/"> {{ post.author.username }} </a><br>
    {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }},
    Группа: {{ post.group }}
</h3>
<p>{{ post.text|linebreaksbr }}</p>
{% if not forloop.last %}
<hr>{% endif %}
{% endfor %}
{% include "paginator.html" %}

{% endblock %}

social_network/templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}


{% for post in page %}
<h3>

    Автор: <a href="/{{ post.author.username }}/"> {{ post.author.username }} </a><br>
    {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
</h3>
<p>{{ post.text|linebreaksbr }}</p>
{% if not forloop.last %}
<hr>{% endif %}
{% endfor %}
{% include "paginator.html" %}

{% endblock %}

social_network/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:darkviolet">Social</span>network</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

social_network/templates/new.html
{% extends "base.html" %}
{% block title %}Создать пост{% endblock %}
{% block content %}

{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Создать пост</div>
            <div class="card-body">

                    {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}

                {% if edit %}
                <form method="post" action="{% url 'post_edit' post.author.username post.id %}">
                {% else %}
                <form method="post" action="{% url 'new_post' %}">
                {% endif %}
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field|addclass:"form-control" }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Создать
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

social_network/templates/paginator.html
{% if page.has_other_pages %}
    <nav>
        <ul class="pagination">
            {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo; Предыдущая</span>
                </li>
            {% endif %}
            {% for i in page.paginator.page_range %}
                {% if page.number == i %}
                    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Следующая &raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

social_network/templates/post.html
{% extends "base.html" %}
{% block title %}Профиль{% endblock %}
{% block header %}Профиль{% endblock %}
{% block content %}


<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                <div class="card">
                        <div class="card-body">
                                <div class="h2">

                                    {{ post.author.get_full_name }}
                                </div>
                                <div class="h3 text-muted">
                                     {{ post.author.username }}
                                </div>
                        </div>
                        <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                        Подписчиков: XXX <br />
                                        Подписан: XXX
                                        </div>
                                </li>
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                            {{ Post.object.count }}
                                        </div>
                                </li>
                        </ul>
                </div>
        </div>

        <div class="col-md-9">

            <!-- Пост -->
                <div class="card mb-3 mt-1 shadow-sm">
                        <div class="card-body">
                                <p class="card-text">
                                        <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                        <a href="/{{ post.author.username }}/">{{ post.author.username }}<strong class="d-block text-gray-dark"></strong></a>
                                        <!-- Текст поста -->

                                        <p> {{ post.text|linebreaksbr }}</p>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group ">
                                                <!-- Ссылка на редактирование, показывается только автору записи -->
                                            {% if user.is_authenticated %}
                                                <a class="btn btn-sm text-muted" href="/{{ post.author.username }}/{{ post.id }}/edit" role="button">Редактировать</a>
                                            {% endif %}
                                        </div>
                                        <!-- Дата публикации  -->
                                        <small class="text-muted">Дата публикации: {{ post.pub_date|date:"d M Y" }}</small>
                                </div>
                        </div>
                </div>
     </div>
    </div>
</main>

{% endblock %}

social_network/templates/profile.html
{% extends "base.html" %}
{% block title %}Профиль{% endblock %}
{% block header %}Профиль{% endblock %}
{% block content %}



<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                    <div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        {{ profile.get_full_name }}
                                    </div>
                                    <div class="h3 text-muted">
                                         Автор: <a href="/{{ profile.username }}/"> {{ profile.username }} </a><br>
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков: XXX <br />
                                            Подписан: XXX
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                                {{ Post.object.count }}
                                            </div>
                                    </li>
                            </ul>
                    </div>
            </div>

            <div class="col-md-9">
{% for post in page %}
                <!-- Начало блока с отдельным постом -->
                    <div class="card mb-3 mt-1 shadow-sm">
                            <div class="card-body">
                                    <p class="card-text">
                                        <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                        <a href="/{{ post.author.username }}/">{{ post.author.username }}<strong class="d-block text-gray-dark"></strong></a>
                                        <!-- Текст поста -->

                                        <p> {{ post.text|linebreaksbr }}</p>
                                </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group ">

                                                    <!-- Ссылка на страницу записи в атрибуте href-->
                                                    <a class="btn btn-sm text-muted" href="/{{ post.author.username }}/{{ post.id }}" role="button">Добавить комментарий</a>
                                                    <!-- Ссылка на редактирование, показывается только автору записи -->
                                                    <a class="btn btn-sm text-muted" href="/{{ post.author.username }}/{{ post.id }}/edit" role="button">Редактировать</a>
                                            </div>
                                            <!-- Дата публикации  -->
                                            <small class="text-muted">Дата публикации: {{ post.pub_date|date:"d M Y" }}</small>
                                    </div>
                            </div>
                    </div>
                <!-- Конец блока с отдельным постом -->

                <!-- Остальные посты -->

                {% endfor %}
                {% include "paginator.html" %}
     </div>
    </div>
</main>
{% endblock %}

social_network/users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}

{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">

                    {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}


                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field|addclass:"form-control" }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}